version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sandy-sam-stepfunction-sync-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6h9see1u3648"
s3_prefix = "sandy-sam-stepfunction-sync-test"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
